### ISSUE TITLE
app/console -bash: __ltrim_colon_completions: command not found

### ISSUE THREAD

**Issue by lsmith77** [bamarni/symfony-console-autocomplete#17]
maybe its colliding with some other auto complete scripts I have for git etc?

**Comment by bamarni** [comment]
not sure, could you give more information about your setup (bash version, os) and how you installed bash completion?

**Comment by c960657** [comment]
Duplicate of #36

**Comment by bamarni** [comment]
@c960657 that's ambitious but there are not that much issues for now 😄 

This function comes from here (https://github.com/scop/bash-completion). I was asking about the environment because how to install / configure it depends on the os. On mac I'm installing it with `brew install bash-completion` then sourcing it in .bashrc : `source $(brew --prefix)/etc/bash_completion`.

I somehow thought this script was a requirement to enable bash completion, but apparently it only provides helper functions. The doc should probably mention this then.

**Comment by c960657** [comment]
Sorry, ignore me. I was confusing this with a similar issue for a different project: https://github.com/stecman/symfony-console-completion/issues/36

**Comment by bamarni** [comment]
I've added a note in the readme (https://github.com/bamarni/symfony-console-autocomplete/commit/50dd456ca8eae8b860e42dfc808dacbc0008a360), @lsmith77 feel free to reopen if you still have the issue.
