### ISSUE TITLE
dynamic completion for fish

### ISSUE THREAD

**Issue by bamarni** [bamarni/symfony-console-autocomplete#25]
cf. https://github.com/fish-shell/fish-shell/issues/3733

**Comment by acidjames** [comment]
Hi @bamarni, is that the solution on how to make sf autocomplete with fish ? Because i don't get it

i've only tried a little but this is what i have with fish : 

`eval (symfony-autocomplete)                                                                                                                                 lun. 06 févr. 2017 09:52:41 CET

                                                                
  [InvalidArgumentException]                                    
  Completion is only available for Bash and Zsh, "fish" given.  
`

thanks in advance,

**Comment by bamarni** [comment]
Hi,

The fish work is currently only on master, you can get it with : 

    composer global require bamarni/symfony-console-autocomplete:dev-master

However only the static completion is available at the moment, for example to get `composer` completion you can do like this : 

    symfony-autocomplete composer > ~/.config/fish/completions/composer.fish

This ticket is about the dynamic completion, I'll check this out soon.

**Comment by rquadling** [comment]
Is this still an issue?

**Comment by rquadling** [comment]
No feedback. Closing.
